// Additional real-browser checks: stale version, refusal and link revocation.
// Same environment variables and fixture format as e2e-real.mjs.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';
const fixture = JSON.parse(fs.readFileSync(process.env.FASE1_FIXTURE, 'utf8'));
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
const base = process.env.FRONTEND_URL || 'http://127.0.0.1:5173';
const backend = process.env.API_URL || 'http://127.0.0.1:8080';
const secrets = [fixture.password];
const request = async (path, token, method = 'GET', body, expected = 200) => {
  const r = await fetch(`${backend}/api/v1${path}`, { method, headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(body ? { 'Content-Type': 'application/json' } : {}) }, body: body ? JSON.stringify(body) : undefined });
  assert.equal(r.status, expected);
  return r.status === 204 ? null : r.json();
};
const browser = await chromium.launch({ headless: true });
try {
  const session = await request('/auth/login', null, 'POST', { oficina: fixture.b.slug, email: fixture.email, senha: fixture.password });
  secrets.push(session.accessToken, session.refreshToken);
  const token = session.accessToken;
  const client = await request('/clientes', token, 'POST', { nome: 'Cliente recusa Fase1', telefone: '11000000000' }, 201);
  const vehicle = await request('/veiculos', token, 'POST', { clienteId: client.id, placa: 'REC' + String(Date.now() % 10000).padStart(4, '0'), marca: 'Fiat', modelo: 'Uno', ano: 2020, km: 0, cor: 'Prata' }, 201);
  const order = await request('/ordens-servico', token, 'POST', { veiculoId: vehicle.id, kmEntrada: 1, relato: 'Teste recusa e versão substituída' }, 201);
  const path = `/ordens-servico/${order.id}`;
  const status = async next => { const current = await request(path, token); await request(`${path}/status`, token, 'POST', { status: next, revisao: current.revisao }); };
  await status('DIAGNOSTICO'); await status('ORCAMENTO');
  const version = async price => request(`${path}/orcamento/versoes`, token, 'POST', { itens: [{ tipo: 'SERVICO', descricao: 'Inspeção', quantidade: 1, valorUnitario: price }] }, 201);
  await version(100); await status('AGUARDANDO_APROVACAO');
  const link = await request(`${path}/links`, token, 'POST', {}, 201); secrets.push(link.token);
  const page = await browser.newPage(); const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(`${base}/acompanhar#${link.token}`);
  await page.getByRole('button', { name: /Aprovar R\$/ }).waitFor();
  await version(200); await status('AGUARDANDO_APROVACAO');
  await page.getByRole('button', { name: /Aprovar R\$/ }).click();
  await page.getByRole('button', { name: 'Confirmar aprovação', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: 'substituído' }).waitFor();
  await page.getByRole('button', { name: 'Atualizar acompanhamento', exact: true }).click();
  await page.getByRole('heading', { name: 'Orçamento · versão 2', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Recusar orçamento', exact: true }).click();
  await page.getByRole('button', { name: 'Confirmar recusa', exact: true }).click();
  await page.getByText('Recusa registrada. A oficina poderá preparar uma nova versão.', { exact: true }).waitFor();
  assert.equal((await request(path, token)).status, 'ORCAMENTO');
  const versions = await request(`${path}/orcamento/versoes`, token);
  assert.equal(versions[1].decisao.aprovado, false);
  console.log('Conflito 409 de versão substituída mostrado; versão atual recusada pelo cliente e persistida.');
  await page.evaluate(() => { window.location.hash = 'token-invalido'; });
  await page.getByText('Solicite um link válido à oficina.', { exact: true }).waitFor();
  assert.equal(await page.getByRole('heading', { name: `Ordem de Serviço #${order.numero}`, exact: true }).count(), 0);
  console.log('Troca de token no fragmento limpa o resumo público anterior.');
  await page.goto(base);
  await page.getByLabel('Oficina', { exact: true }).fill(fixture.b.slug);
  await page.getByLabel('E-mail', { exact: true }).fill(fixture.email);
  await page.locator('input[name="senha"]').fill(fixture.password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await page.getByRole('heading', { name: 'Um dia bem organizado.', exact: true }).waitFor();
  await page.getByRole('navigation', { name: 'Navegação principal', exact: true }).getByRole('button', { name: 'Ordens de Serviço', exact: true }).click();
  await page.getByRole('button', { name: `Abrir OS ${order.numero}`, exact: true }).click();
  await page.getByRole('tab', { name: 'Orçamento', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Buscar na oficina', exact: true }).click();
  await page.getByRole('textbox', { name: 'OS, placa, veículo ou cliente', exact: true }).fill(String(order.numero));
  await page.getByRole('dialog').getByRole('button', { name: new RegExp(`^OS #${order.numero}\\b`) }).click();
  await page.getByRole('tab', { name: 'Orçamento', exact: true }).waitFor();
  console.log('Reabrir a mesma OS pela busca global mantém o detalhe disponível.');
  await page.getByRole('tab', { name: 'Orçamento', exact: true }).click();
  await page.getByRole('button', { name: 'Gerar link do cliente', exact: true }).click();
  const field = page.getByLabel('Link do cliente', { exact: true }); await field.waitFor();
  const issued = new URL(await field.inputValue()).hash.slice(1); secrets.push(issued);
  await page.getByRole('button', { name: 'Revogar link', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Revogar link', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await request(`/publico/${issued}`, null, 'GET', undefined, 404);
  console.log('Link emitido e revogado pela interface; consulta posterior recebe 404.');
  assert.deepEqual(errors, []);
  await request('/auth/logout', null, 'POST', { oficinaId: session.oficinaId, refreshToken: session.refreshToken }, 204);
  const output = process.env.E2E_OUTPUT || '../.tools/fase1-e2e';
  fs.mkdirSync(output, { recursive: true });
  fs.writeFileSync(`${output}/publico.json`, JSON.stringify({ versaoSubstituida: 409, recusa: 'persistida', revogacao: 404, errors }, null, 2));
} catch (error) {
  let message = String(error.stack || error);
  for (const secret of secrets.filter(Boolean)) message = message.split(secret).join('[REDACTED]');
  console.error(message); process.exitCode = 1;
} finally { await browser.close(); }
